In [1]:
import numpy as np
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Sequential

In [2]:
X = np.array([
             [0, 0],
             [0, 1],
             [1, 0],
             [1, 1],
             ])
y = np.array([0,1,1,0])
X, y

(array([[0, 0],
        [0, 1],
        [1, 0],
        [1, 1]]),
 array([0, 1, 1, 0]))

In [34]:
model = Sequential()
model.add(Dense(32, activation='sigmoid', input_dim=2))
model.add(Dense(1, activation='sigmoid'))

In [35]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['acc'])

In [36]:
model.summary()

Model: "sequential_5"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_10 (Dense)             (None, 32)                96        
_________________________________________________________________
dense_11 (Dense)             (None, 1)                 33        
Total params: 129
Trainable params: 129
Non-trainable params: 0
_________________________________________________________________


In [40]:
model.fit(X, y, epochs=1000, verbose=0)

In [41]:
model.evaluate(X, y)

1/1 [==============================] - 0s 3ms/step - loss: 0.1804 - acc: 1.0000


[0.1804034411907196, 1.0]

In [42]:
model.predict(X)

array([[0.13043445],
       [0.8308027 ],
       [0.83711696],
       [0.19643548]], dtype=float32)